name: Publish compiled packages
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
        contents: write
    steps:
      - uses: oven-sh/setup-bun@v2
      - uses: actions/checkout@v4
      - name: Create tag
        id: create_tag
        run: |
          tag_name="v1.0.${{ github.run_number }}"
          git tag $tag_name
          git push origin $tag_name
      - run: bun i
      - run: bun build ./index.ts --compile --minify --target=bun-linux-x64-modern --outfile autopgp-linux
      - run: bun build ./index.ts --compile --minify --target=bun-windows-x64-modern --outfile autopgp-windows.exe
      - name: Release
        uses: softprops/action-gh-release@v2.2.1
        with:
          tag_name: v1.0.${{ github.run_number }}
          files: |
            autopgp-linux
            autopgp-windows.exe