name: compile
on:
  workflow_dispatch:
    inputs:
      versionNumber:
        description: "Version number to use in tag"
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: create tag
        id: create_tag
        run: |
          tag_name=${{ inputs.versionNumber }}
          git tag $tag_name
          git push origin $tag_name
      - name: go setup
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.4
      - name: install deps
        run: go get .
      - name: compile-linux
        env:
          GOOS: linux
          GOARCH: amd64
          GOAMD64: v3
        run: go build -ldflags "-s -w" -o autopgp
      - name: compile-win
        env:
          GOOS: windows
          GOARCH: amd64
          GOAMD64: v3
        run: go build -ldflags "-s -w" -o autopgp.exe
      - name: release
        uses: softprops/action-gh-release@v2.3.2
        with:
          tag_name: ${{ inputs.versionNumber }}
          files: |
            autopgp.exe
            autopgp
